name = "redox_steady_state_aquifers"
authors = ["Vitor Cantarella, Adrian Mellage & Olaf Cirpka"]
[compat]
julia = "1.11.0"
DrWatson = "2.18.0"
[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
